# Generated by Django 5.2.7 on 2025-10-09 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostelinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=200)),
                ('total_floors', models.IntegerField()),
                ('building_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_type', models.CharField(choices=[('fan', 'Fan'), ('ac', 'AC'), ('geyser', 'Geyser'), ('tv', 'TV'), ('light', 'Light')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField()),
                ('total_rooms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hostelmanagement.building')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='hostelinfo.user')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='hostelmanagement.hostel'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('AC', 'AC'), ('NON_AC', 'NON_AC')], max_length=10, null=True)),
                ('preference', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('total_beds', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_rent', models.CharField(blank=True, max_length=20, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostelmanagement.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('monthly_rent', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostelmanagement.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelmanagement.inventory')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelmanagement.room')),
            ],
            options={
                'unique_together': {('room', 'inventory')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='inventories',
            field=models.ManyToManyField(related_name='rooms', through='hostelmanagement.RoomInventory', to='hostelmanagement.inventory'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhar_image', models.FileField(blank=True, null=True, upload_to='aadhar/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelmanagement.bed')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostelinfo.user')),
            ],
        ),
    ]
