# Generated by Django 5.2.7 on 2025-10-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='hostel_type',
        ),
        migrations.AddField(
            model_name='building',
            name='building_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coliving', 'coliving')], max_length=10),
        ),
    ]
