# Generated by Django 5.2.7 on 2025-10-09 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectFee',
            fields=[
                ('fee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('Deposit_Only', 'Deposit Only'), ('Advance_Only', 'Advance Only'), ('Deposit_Advance', 'Deposit + Advance'), ('Monthly_Rent', 'Monthly Rent')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank'), ('card', 'Card')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='hostelmanagement.student')),
            ],
        ),
    ]
