# Generated by Django 5.2.7 on 2025-10-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectfee',
            old_name='status',
            new_name='payment_method',
        ),
    ]
