# Generated by Django 5.2.7 on 2025-10-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feemanagement', '0002_rename_status_collectfee_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectfee',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='collectfee',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collectfee',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
