"""
Django settings for hostelbackend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from core.env import BASE_DIR, env

env.read_env(os.path.join(BASE_DIR, ".env"))
import dj_database_url

# Cloudinary configuration
CLOUDINARY_URL = env("CLOUDINARY_URL", default=None)
if CLOUDINARY_URL:
    # Parse CLOUDINARY_URL format: cloudinary://api_key:api_secret@cloud_name
    import re
    match = re.match(r'cloudinary://(\d+):([^@]+)@([^/]+)', CLOUDINARY_URL)
    if match:
        os.environ['CLOUDINARY_API_KEY'] = match.group(1)
        os.environ['CLOUDINARY_API_SECRET'] = match.group(2)
        os.environ['CLOUDINARY_CLOUD_NAME'] = match.group(3)
# from dotenv import load_dotenv


# load_dotenv(BASE_DIR / ".env")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = ["*", "06e6135d4866.ngrok-free.app", "hostelbe-53823350765.us-central1.run.app","hostelbe-production-53823350765.asia-south1.run.app", "hostelbetesting.managemyhostels.com", "hostelbe.managemyhostels.com","hostelbe-production-53823350765.us-east1.run.app","hostel-backend-prod-53823350765.us-east1.run.app"]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://hostelapp-backend.onrender.com",
    "https://06e6135d4866.ngrok-free.app",
    "https://hostelbe-53823350765.us-central1.run.app",
    "https://hostelapp-53823350765.asia-south1.run.app",
    "https://hostelbe-production-53823350765.asia-south1.run.app",
    "https://hostelbetesting.managemyhostels.com",
    "https://hostelbe.managemyhostels.com",
    "https://hostelbe-production-53823350765.us-east1.run.app",
    "https://hostel-backend-prod-53823350765.us-east1.run.app"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:8000",
    "https://hostelapp-backend.onrender.com",
    "https://06e6135d4866.ngrok-free.app",
    "https://hostelbe-53823350765.us-central1.run.app",
    "https://hostelapp-53823350765.asia-south1.run.app",
    "https://hostelbe-production-53823350765.asia-south1.run.app",
    "https://hostelbetesting.managemyhostels.com",
    "https://hostelbe.managemyhostels.com",
    "https://hostelbe-production-53823350765.us-east1.run.app",
    "https://hostel-backend-prod-53823350765.us-east1.run.app"
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True



# Application definition

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "apps.hostelinfo",
    "apps.hostelmanagement",
    'apps.roomallocate',
    'apps.feemanagement',
    'apps.reports',
    'apps.messmanagement',
    'apps.expenses',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.hostelbackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.hostelbackend.wsgi.application"


# Database
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "postgres",
#         "USER": "postgres.vzrpojilawtpoipwygse",
#         "PASSWORD": "1234",
#         "HOST": "aws-1-us-east-2.pooler.supabase.com",
#         "PORT": "5432",
#         "OPTIONS": {
#             "sslmode": "require"
#         }
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST= 'smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER= '2000031980cse@gmail.com'
EMAIL_HOST_PASSWORD= 'fbifhwavzuxbobav'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'


# AWS S3

AWS_ACCESS_KEY_ID = 'AKIA3M3SGEUDS2KJTTHY'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'hosteldocuments'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


#  LOGGING
# Ensure logs directory exists
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "django.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "hostelinfo": {  # Example for one app
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
