"""
Django settings for hostelbackend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# import dj_database_url
# from dotenv import load_dotenv

# load_dotenv(BASE_DIR / ".env")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-d-cd=^6y2d+t4oo9#dv-g--aah_gbjglttaozj^p(0x%v^d3=!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "*", "0cad3b15d340.ngrok-free.app","hostelbackend.prajwalynxfinovations.com","3.94.166.124","hostelbe-production-53823350765.asia-south1.run.app","hostelbetesting.managemyhostels.com","hostelbe.managemyhostels.com","hostelbe-production-53823350765.us-east1.run.app","hostel-backend-prod-53823350765.us-east1.run.app"]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://32bee17cad98.ngrok-free.app",
    "https://hostelapp-backend.onrender.com",
    "https://0cad3b15d340.ngrok-free.app",
    "https://hostelbackend.prajwalynxfinovations.com",
    "http://3.94.166.124:8000",
    "https://hostelbe-53823350765.us-central1.run.app",
    "https://hostelapp-53823350765.asia-south1.run.app",
    "https://hostelbe-production-53823350765.asia-south1.run.app",
    "https://hostelbetesting.managemyhostels.com",
    "https://hostelbe.managemyhostels.com",
    "https://hostelbe-production-53823350765.us-east1.run.app",
    "https://hostel-backend-prod-53823350765.us-east1.run.app"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:8000",
    "https://32bee17cad98.ngrok-free.app",
    "https://hostelapp-backend.onrender.com",
    "https://0cad3b15d340.ngrok-free.app",
    "https://hostelbackend.prajwalynxfinovations.com",
    "http://3.94.166.124:8000",
    "https://hostelbe-53823350765.us-central1.run.app",
    "https://hostelapp-53823350765.asia-south1.run.app",
    "https://hostelbe-production-53823350765.asia-south1.run.app",
    "https://hostelbetesting.managemyhostels.com",
    "https://hostelbe.managemyhostels.com",
    "https://hostelbe-production-53823350765.us-east1.run.app",
    "https://hostel-backend-prod-53823350765.us-east1.run.app"
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "apps.hostelinfo",
    "apps.hostelmanagement",
    'apps.roomallocate',
    'apps.feemanagement',
    'apps.messmanagement',
    'apps.reports',
    'apps.expenses',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.hostelbackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.hostelbackend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("POSTGRES_DB", "hostel_db"),
#         "USER": os.environ.get("POSTGRES_USER", "postgres"),
#         "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
#         "HOST": os.environ.get("POSTGRES_HOST", "db"),
#         "PORT": os.environ.get("POSTGRES_PORT", "5432"),
#     }
# }

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "2000031980cse@gmail.com"
EMAIL_HOST_PASSWORD = "fbifhwavzuxbobav"
