# Generated by Django 5.2.7 on 2025-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('premium', 'Premium')], default='free_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
