# Generated by Django 5.2.7 on 2025-10-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelinfo', '0003_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
    ]
