# Generated by Django 5.2.7 on 2025-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelinfo', '0004_remove_user_account_status_remove_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reciept',
            field=models.FileField(blank=True, null=True, upload_to='reciepts/'),
        ),
    ]
