# Generated by Django 5.2.7 on 2025-10-29 13:16

import core.settings.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelinfo', '0005_subscription_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='reciept',
            field=models.FileField(blank=True, null=True, storage=core.settings.cloudinary_storage.CloudinaryStorage(), upload_to='reciepts/'),
        ),
    ]
