# Generated by Django 5.2.7 on 2025-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='building_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
