# Generated by Django 5.2.7 on 2025-10-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_building_id'),
        ('hostelmanagement', '0002_remove_hostel_address_remove_hostel_hostel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='building_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='hostelmanagement.building'),
        ),
    ]
