# Generated by Django 5.2.7 on 2025-10-09 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostelinfo', '0001_initial'),
        ('hostelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_students', to='hostelinfo.user')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostelmanagement.bed')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostelmanagement.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostelinfo.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoomIssues',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('water', 'Water Problem'), ('electricity', 'Electricity Issue'), ('cleaning', 'Cleaning Issue'), ('wifi', 'Wi-Fi Issue'), ('furniture', 'Furniture Damage'), ('other', 'Other')], max_length=50)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_status', models.CharField(choices=[('in_progress', 'In Progress'), ('solved', 'Solved'), ('not_solved', 'Not Solved')], default='in_progress', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_issues', to='hostelmanagement.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_issues', to='hostelinfo.user')),
            ],
        ),
    ]
